 export const Country = [
  { CountryName: "Algeria" },
  { CountryName: "Angola" },
  { CountryName: "Benin" },
  { CountryName: "Botswana" },
  { CountryName: "Burkina Faso" },
  { CountryName: "Burundi" },
  { CountryName: "Cape Verde" },
  { CountryName: "Cameroon" },
  { CountryName: "Central African Republic" },
  { CountryName: "Chad" },
  { CountryName: "Comoros" },
  { CountryName: "Democratic Republic of the Congo" },
  { CountryName: "Republic of the Congo" },
  { CountryName: "Djibouti" },
  { CountryName: "Egypt" },
  { CountryName: "Equatorial Guinea" },
  { CountryName: "Eritrea" },
  { CountryName: "Ethiopia" },
  { CountryName: "Côte d’Ivoire (Ivory Coast)" },
  { CountryName: "Gabon" },
  { CountryName: "Gambia" },
  { CountryName: "Ghana" },
  { CountryName: "Guinea" },
  { CountryName: "Guinea-Bissau" },
  { CountryName: "Kenya" },
  { CountryName: "Lesotho" },
  { CountryName: "Liberia" },
  { CountryName: "Libya" },
  { CountryName: "Madagascar" },
  { CountryName: "Malawi" },
  { CountryName: "Mali" },
  { CountryName: "Mauritania" },
  { CountryName: "Mauritius" },
  { CountryName: "Morocco" },
  { CountryName: "Mozambique" },
  { CountryName: "Namibia" },
  { CountryName: "Niger" },
  { CountryName: "Nigeria" },
  { CountryName: "Rwanda" },
  { CountryName: "Sao Tome and Principe" },
  { CountryName: "Senegal" },
  { CountryName: "Seychelles" },
  { CountryName: "Sierra Leone" },
  { CountryName: "Somalia" },
  { CountryName: "South Africa" },
  { CountryName: "South Sudan" },
  { CountryName: "Sudan" },
  { CountryName: "Tanzania" },
  { CountryName: "Togo" },
  { CountryName: "Tunisia" },
  { CountryName: "Uganda" },
  { CountryName: "Zambia" },
  { CountryName: "Zimbabwe" },
];
